
name: Firma de código con DigiCert ONE

on:
  workflow_dispatch:

jobs:
  sign-code:
    runs-on: ubuntu-22.04

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

    
      - name: Descomprimir DigiCert Signing Manager Tools
        run: |
          mkdir -p /tmp/digicert-tools
          tar -xzf tools/smtools-linux-x64.tar.gz -C /tmp/digicert-tools

          
          
      - name: Verificar contenido descomprimido
        run: |
          echo "Contenido de /tmp/digicert-tools:"
          ls -l /tmp/digicert-tools
          echo "Contenido de subcarpetas:"
          find /tmp/digicert-tools



      - name: Verificar certificados disponibles con smktool
        run: |
          echo "Listando certificados disponibles con smktool..."
          /tmp/digicert-tools/smtools-linux-x64/smktool list-certificates
  


      - name: Firmar archivo con DigiCert
        uses: cognitedata/code-sign-action@v3
        with:
          path-to-binary: winpty.exe
        env:
          CERTIFICATE_HOST: ${{ secrets.SM_HOST }}
          CERTIFICATE_HOST_API_KEY: ${{ secrets.SM_API_KEY }}
          CERTIFICATE_SHA1_HASH: ${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }}
          CLIENT_CERTIFICATE: ${{ secrets.SM_CLIENT_CERT_FILE }}
          CLIENT_CERTIFICATE_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
          KEYPAIR_ALIAS: ${{ secrets.SM_KEYPAIR_ALIAS }}

