
name: Firma de código con DigiCert ONE

on:
  workflow_dispatch:

jobs:
  sign-code:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
        
        
        
      - name: Firmar archivo con DigiCert
        uses: digicert/software-trust-manager-code-sign@v1
        with:
          inputFile: archivo_a_firmar.dll
          outputFile: archivo_firmado.dll
        env:
          SM_API_KEY: ${{ secrets.SM_API_KEY }}
          SM_CLIENT_CERT_FILE: ${{ secrets.SM_CLIENT_CERT_FILE }}
          SM_CLIENT_CERT_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
          SM_CODE_SIGNING_CERT_SHA1_HASH: ${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }}
          SM_HOST: ${{ secrets.SM_HOST }}


      - name: Subir archivo firmado como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-firmado
          path: archivo_firmado.ext
