
name: Firma de código con DigiCert ONE

on:
  workflow_dispatch:

jobs:
  sign-code:
    runs-on: ubuntu-22.04

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
        
        
      
      - name: Instalar jsign
        run: |
          curl -fSslL https://github.com/ebourg/jsign/releases/download/3.1/jsign_3.1_all.deb -o jsign_3.1_all.deb
          sudo dpkg -i jsign_3.1_all.deb

      - name: Listar certificados en el keystore PKCS#11
        run: |
          echo "Listando certificados disponibles en el keystore PKCS#11..."
          jsign --keystore "/tmp/DigiCert One Signing Manager Tools/smtools-linux-x64/pkcs11properties.cfg" \
                --storetype PKCS11 \
                --storepass NONE \
                --list



      - name: Firmar archivo con DigiCert
        uses: cognitedata/code-sign-action@v3
        with:
          path-to-binary: winpty.exe
        env:
          CERTIFICATE_HOST: ${{ secrets.SM_HOST }}
          CERTIFICATE_HOST_API_KEY: ${{ secrets.SM_API_KEY }}
          CERTIFICATE_SHA1_HASH: ${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }}
          CLIENT_CERTIFICATE: ${{ secrets.SM_CLIENT_CERT_FILE }}
          CLIENT_CERTIFICATE_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
          KEYPAIR_ALIAS: ${{ secrets.SM_KEYPAIR_ALIAS }}

