name: Sign Code with DigiCert Software Trust Manager

on:
  push:
    branches:
      - main

jobs:
  sign-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install DigiCert Client tools from Github Custom Actions marketplace
        id: Plugin
        uses: digicert/ssm-code-signing@v1.1.0
        env:
          FORCE_DOWNLOAD_TOOLS: 'true'
